" ------------------------------------------------------
" file:     $HOME/.config/vim/vimrc
" author:   Ramon Solis  
" modified: Nov 2017
" vim:fenc=utf-8:nu:ai:si:et:ts=4:sw=4:ft=vim:
" ------------------------------------------------------

set t_Co=256            " Enable 256 colors
"colorscheme xoria256    " Set the colorscheme
set nocompatible 	    " VIM

set viminfo+=n$HOME/.config/vim/viminfo
set backupdir=$HOME/.config/vim/backup
set runtimepath=$HOME/.config/vim,$VIMRUNTIME
let $MYVIMRC="$HOME/.config/vim/vimrc"

" -----------
" colorscheme
" -----------
"
"if !has("gui_running")
"    colorscheme zenburn
"endif

set nocompatible 	    " This is fucking vim
"colorscheme herald
set background=dark     " Darky
set number              " Set numbers 
set showmatch		    " Show matching brackets

filetype off
filetype plugin on
syntax on

set backspace=indent,eol,start " Make backspace work as usual
set tabstop=4

set shiftwidth=4
set encoding=utf-8 	    " Unicode support
set novisualbell 	    " Don't blink

" ------
" Indent
" ------
set autoindent          " Auto indenting
set smartindent 	    " Smart indenting 

" -----------
" Status line
" -----------
set showcmd 		    " Show (partial) command in status line
set showmode            " Show mode in status line
set cmdheight=1         " Set height of command
set laststatus=2 	    " Always show the status line
set statusline=\ \%f%m%r%h%w\ ::\ %y\ [%{&ff}]\%=\ [%p%%:\ %l/%L]\  " Credits to http://jasonwryan.com/


set mat=5   		    " How many tenths of a second to blink matching brackets for

" ------
" Search
" ------
set nohlsearch 		    " Do not highlight the string we searched
set incsearch 			" Incremental search: Highlight the searched string, while typing
set ignorecase          " Case-insensitive search
set smartcase           " Upper-case sensitive search
set wrapscan            " searches wrap back to the top of file

set fileformats=unix	" 
set ruler
set wrap                " wrap long lines to fit terminal width
set backupdir=~/.config/vim/backup  " 
set updatecount=200
set autochdir
set ttyfast             " tell vim we're using a fast terminal for redraws
set autoread            " Reload file if vim detects it changed elsewhere
set shell=/usr/bin/zsh  " Default shell type
set nobackup            " Disable backup
set swapfile
set updatecount=200
set autochdir
set ttyfast             " tell vim we're using a fast terminal for redraws
set autoread            " Reload file if vim detects it changed elsewhere
set shell=/bin/zsh      " Default shell type
set history=666         " Lines of command history
set undolevels=666      " Set undo level
set title               " Set window title with the vim file
set ofu=syntaxcomplete#Complete
set nostartofline       " remember the cursor position
set lazyredraw

" Remember cursor last position
au BufWinLeave ?* mkview
au BufWinEnter ?* silent loadview
"set spell
"set colorcolumn=120

" --------
" NERDTree
" --------
" autocmd VimEnter * NERDTree " Start NERDTree 
" autocmd VimEnter * wincmd p " Focus on main window
let NERDTreeWinSize=25  " Increase window size to 35 columns
nmap <silent> <F7> :NERDTreeToggle<CR> " map <F7> to toggle NERDTree window
let NERDTreeShowHidden=1    " Show hidden files 

" -------------
" mapping stuff
" -------------
":nmap <C-t> :tabnew .<CR>
":imap <C-t> <Esc>:tabnew .<CR>

" H & L to navigate trough the tabs
:map <S-h> gT
:map <S-l> gt

filetype plugin indent on
" :nmap <C-t> :tabnew .<CR>
" :imap <C-t> <Esc>:tabnew .<CR>
" :map <C-w> :tabclose<CR>

" H|L to navigate trough the tabs
:map <S-h> gT
:map <S-l> gt

":nmap <C-a> :%y<CR>     " Yank all
":nmap <C-d> :1,$d<CR>   " Delete all
":map <C-o> O<Esc><CR>


syn match ipaddr /\(\(25\_[0-5]\|2\_[0-4]\_[0-9]\|\_[01]\?\_[0-9]\_[0-9]\?\)\.\)\{3\}\(25\_[0-5]\|2\_[0-4]\_[0-9]\|\_[01]\?\_[0-9]\_[0-9]\?\)/
hi link ipaddr Identifier


" Toggle Vexplore with Ctrl-E
function! ToggleVExplorer()
    if exists("t:expl_buf_num")
        let expl_win_num = bufwinnr(t:expl_buf_num)
        if expl_win_num != -1
            let cur_win_nr = winnr()
            exec expl_win_num . 'wincmd w'
            close
            exec cur_win_nr . 'wincmd w'
            unlet t:expl_buf_num
        else
            unlet t:expl_buf_num
        endif
    else
        exec '1wincmd w'
        Vexplore
        let t:expl_buf_num = bufnr("%")
    endif
endfunction
map <silent> <C-E> :call ToggleVExplorer()<CR>


" Hit enter in the file browser to open the selected
" file with :vsplit to the right of the browser.
let g:netrw_browse_split = 4
let g:netrw_altv = 1

" Default to tree mode
let g:netrw_liststyle=3
"
" Change directory to the current buffer when opening files.
set autochdir
